### ISSUE TITLE
popup resultat

### ISSUE THREAD

**Issue by simonbertin** [alexisfouquet/BlackOrRed#1]
Afficher le résultat dans une popup en gros au milieu de l'écran

**Comment by alexisfouquet** [comment]
J'aime bien l'idée surtout que dans ce popup on pourrait mettre les contrôles permettant de donner les coups quand on en a à donner. Par contre le popup va potentiellement cacher le jeu c'est ça qui me dérange. Genre la carte apparaît et le popup la cache, du coup tu sais que tu as perdu ou gagné mais tu ne sais pas pourquoi!

Du coup dans ma tête je suis plus partie sur une barre un bas de l'écran, l'équivalent des snackbars dans android. Je vais faire des essais pour voir.

**Comment by alexisfouquet** [comment]
J'ai amélioré l'affichage du résultat en mettant le joueur en rouge si réussite ou noir si échec, et je permet également d'attribuer les coups ce qui montre de façon assez évidente qu'on a gagné.

Je préfère cette solution au popup qui en fait masque le résultat et rend le jeu moins fluide. A confirmer lors de la prochaine phase de test.

**Comment by simonbertin** [comment]
Trop bien de pouvoir distribuer !
Par contre la souris fait beaucoup de chemin, (dans le jeux pour choisir, en bas à gauche pour distribuer, en base a droite pour valider puis en haut a droite pour "c'est bu")
Es ce que mettre tout les "clics" au même endroit est facilement faisable ?

**Comment by alexisfouquet** [comment]
Je vois ce que tu veux dire j'avais pensé pareil. Mais le truc c'est que la barre du haut est déjà bien remplie et la barre de distribution a besoin de place. Par exemple avec 7 joueurs sur mon écran 13 pouces :
![image](https://user-images.githubusercontent.com/58078835/79212917-3c20a300-7e40-11ea-8a7f-c087d55a341a.png)

Peut-être en mettant la barre de distribution en haut comme ça mais je trouve ça moins beau :
![image](https://user-images.githubusercontent.com/58078835/79213469-22cc2680-7e41-11ea-8f88-8756eeb7c520.png)

**Comment by alexisfouquet** [comment]
Ou c'est peut être un coup d'habitude à prendre... Je vais faire l'essai avec la barre en haut mais déjà techniquement je ne sais pas comment faire ^^ (je l'ai fait avec paint pour le screenshot ^^)

**Comment by alexisfouquet** [comment]
C'est bon j'ai mis la barre en haut et effectivement c'est beaucoup plus pratique!
