### ISSUE TITLE
badges de fin de partie

### ISSUE THREAD

**Issue by simonbertin** [alexisfouquet/BlackOrRed#3]
À la fin, afficher des stat
-le biflon : Celui qui a le plus bu
-la fouine : Celui à qui a le moins bu
-Le pigeon : celui à qui on a le plus distribué
-cocu : celui qui a trouvé le plus de carte (et qui a le moins bu à la piramide)
-cleopatre : celui qui a le moins bu à la piramide
-Numerobis : celui qui a le plus distribué : "Bande de chacals, vous allez crever comme des chacals". Mais ça faisait deux fois "chacals"... Quoi, on dit des "chacaux" ?

**Comment by alexisfouquet** [comment]
Vraiment stylé les noms!
Je dirais plutôt que le pigeon c'est celui qui s'est le plus trompé, et tombé sur des cartes rouges à la pyramide), donc l'inverse du cocu quoi. Et celui à qui on a le plus distribué serait "La victime"

**Comment by alexisfouquet** [comment]
Je vais partir la dessus mais c'est améliorable :)

![image](https://user-images.githubusercontent.com/58078835/79057565-8811f300-7c5a-11ea-9059-469f0490e90c.png)

**Comment by alexisfouquet** [comment]
Ah et dans les badges spéciaux on peut ajouter l'inverse du stratège, qui a le pire golvérage. Genre "L'idiot du village" ^^

**Comment by alexisfouquet** [comment]
Mis à jour :)

![image](https://user-images.githubusercontent.com/58078835/79057609-1b4b2880-7c5b-11ea-90e9-78bc3ade8c6c.png)

**Comment by simonbertin** [comment]
Il faudrait rajouter la description dans les badges !

**Comment by alexisfouquet** [comment]
Oui oui je vais faire un truc plus complet et joli, c'est en cours ;)

**Comment by simonbertin** [comment]
J'ai fais un truc mais c'est très basique^^

**Comment by alexisfouquet** [comment]
Oui j'ai vu! :) C'est cool si je suis pas tout seul!!! :)

J'étais parti sur un truc dans ce genre, c'est pas un peu plus "immersif" qu'une légende ?

![image](https://user-images.githubusercontent.com/58078835/79228122-d8ef3a80-7e58-11ea-879e-4b771d9e31b1.png)

C'est encore moche mais dans l'idée t'en penses quoi?

**Comment by simonbertin** [comment]
^^ trop bien.
C'est bien mieux que mon truc !
Vu mon niveau en js je ne vais pas beaucoup t'aider !

**Comment by alexisfouquet** [comment]
Ben quand même t'as direct compris comment marchait mon tableau et t'as pigé comment écrire de l'html avec js :)

**Comment by alexisfouquet** [comment]
![image](https://user-images.githubusercontent.com/58078835/79375693-eee02680-7f50-11ea-81f1-180ea00a8764.png)

Après pas mal de taff j'arrive à ça ! :)

**Comment by simonbertin** [comment]
Tu gère comment les égalités ?

**Comment by simonbertin** [comment]
Mais ca claque en tout cas !

**Comment by simonbertin** [comment]
Pour la victime, t'as l'info de celui qui lui en a donné le plus.
"avec 15 coup reçu (don 14 de Alexis), Rodolphe est la victime"

On pourrais d’ailleurs faire une matrice de qui a donné a qui^^

**Comment by alexisfouquet** [comment]
Ben je les gère pas mais il faudrait ! On va dire que tel que c'est fait, si il y a égalité, c'est le joueur le plus en début de liste qui va être choisi.

**Comment by alexisfouquet** [comment]
Non actuellement, les coups reçus par une personne c'est juste un compteur qui s'incrémente mais oui j'adore l'idée ! Pour ça il faut donc transformer le compteur de coups reçus en un tableau d'une structure contenant le nom du joueur donneur et le nombre de coups donnés
